/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewCRTemplate.java
 *
 * Created on Sep 23, 2009, 9:53:47 AM
 */

package com.sabre.hd.gui;

import com.sabre.hd.easysr.Facade;
import com.sabre.hd.easysr.entities.ChangeRequest;
import com.sabre.hd.easysr.forms.EcpmNewChange;
import com.sabre.hd.easysr.forms.EdssrtServiceRequest;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SG0203703
 */
public class NewCRTemplate extends javax.swing.JFrame {

    /** Creates new form NewCRTemplate */
    public NewCRTemplate() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlActions = new javax.swing.JPanel();
    btnClose = new javax.swing.JButton();
    btnNew = new javax.swing.JButton();
    btnLoad = new javax.swing.JButton();
    btnSave = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    tbsCRForm = new javax.swing.JTabbedPane();
    pnlContactInformation = new javax.swing.JPanel();
    jLabel27 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    cmbEnvironment = new javax.swing.JComboBox();
    cmbSponsor = new javax.swing.JComboBox();
    cmbRequestedType = new javax.swing.JComboBox();
    jLabel6 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    txtManagerID = new javax.swing.JTextField();
    txtChangeCategory = new javax.swing.JTextField();
    jLabel24 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtImpactDescription = new javax.swing.JTextArea();
    jScrollPane10 = new javax.swing.JScrollPane();
    txtChangeJustification = new javax.swing.JTextArea();
    jLabel33 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    cmbCurrentStatus = new javax.swing.JComboBox();
    cmbChangeName = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel29 = new javax.swing.JLabel();
    txtPhoneNumber = new javax.swing.JTextField();
    cmbState = new javax.swing.JComboBox();
    jLabel12 = new javax.swing.JLabel();
    txtExternalReferenceID = new javax.swing.JTextField();
    jLabel31 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jScrollPane7 = new javax.swing.JScrollPane();
    txtDescription = new javax.swing.JTextArea();
    txtAssociatedProblem = new javax.swing.JTextField();
    pnlClassification = new javax.swing.JPanel();
    jLabel28 = new javax.swing.JLabel();
    txtImplementationLocation = new javax.swing.JTextField();
    jLabel25 = new javax.swing.JLabel();
    txtHSIS = new javax.swing.JTextField();
    jScrollPane11 = new javax.swing.JScrollPane();
    txtRiskReason = new javax.swing.JTextArea();
    txtOther = new javax.swing.JTextField();
    txtECO = new javax.swing.JTextField();
    txtLMR = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel30 = new javax.swing.JLabel();
    cmbComponentType = new javax.swing.JComboBox();
    txtEmployeeID = new javax.swing.JTextField();
    cmbActivity = new javax.swing.JComboBox();
    jLabel32 = new javax.swing.JLabel();
    cmbPriority = new javax.swing.JComboBox();
    jTextField5 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    cmbDeveloperVendor = new javax.swing.JComboBox();
    jScrollPane2 = new javax.swing.JScrollPane();
    cmbAssets = new javax.swing.JList();
    jLabel14 = new javax.swing.JLabel();
    txtEmailAddress = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    txtCustomersImpacted = new javax.swing.JTextField();
    chkFirewallChange = new javax.swing.JCheckBox();
    pnlImpactAndRisk = new javax.swing.JPanel();
    chkEmergencyChange = new javax.swing.JCheckBox();
    chkAffectsMultiplyCustomers = new javax.swing.JCheckBox();
    chkSignificantChange = new javax.swing.JCheckBox();
    chkAffectsCritical = new javax.swing.JCheckBox();
    chkTechnicalTeam = new javax.swing.JCheckBox();
    chkNewActivity = new javax.swing.JCheckBox();
    jLabel20 = new javax.swing.JLabel();
    txtCustomerImpact = new javax.swing.JTextField();
    jRadioButton14 = new javax.swing.JRadioButton();
    jRadioButton13 = new javax.swing.JRadioButton();
    jLabel46 = new javax.swing.JLabel();
    jRadioButton16 = new javax.swing.JRadioButton();
    jRadioButton18 = new javax.swing.JRadioButton();
    jRadioButton15 = new javax.swing.JRadioButton();
    jRadioButton17 = new javax.swing.JRadioButton();
    jRadioButton5 = new javax.swing.JRadioButton();
    jLabel61 = new javax.swing.JLabel();
    jRadioButton20 = new javax.swing.JRadioButton();
    jRadioButton6 = new javax.swing.JRadioButton();
    jRadioButton19 = new javax.swing.JRadioButton();
    pnlInstallaionAndFallback = new javax.swing.JPanel();
    txtDurationHH = new javax.swing.JTextField();
    txtDurationDD = new javax.swing.JTextField();
    jLabel40 = new javax.swing.JLabel();
    txtDurationMM = new javax.swing.JTextField();
    jLabel42 = new javax.swing.JLabel();
    jLabel41 = new javax.swing.JLabel();
    chkASAP = new javax.swing.JCheckBox();
    chkDefault = new javax.swing.JCheckBox();
    txtStartDate = new javax.swing.JTextField();
    txtEndDate = new javax.swing.JTextField();
    jLabel36 = new javax.swing.JLabel();
    jLabel39 = new javax.swing.JLabel();
    txtEndTime = new javax.swing.JTextField();
    txtStartTime = new javax.swing.JTextField();
    jLabel38 = new javax.swing.JLabel();
    jLabel37 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jLabel34 = new javax.swing.JLabel();
    jLabel35 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    txtInstallationProcedure = new javax.swing.JTextArea();
    jScrollPane4 = new javax.swing.JScrollPane();
    txtFallbackProcedure = new javax.swing.JTextArea();
    pnlSupportContact = new javax.swing.JPanel();
    txtInstallerID = new javax.swing.JTextField();
    jLabel50 = new javax.swing.JLabel();
    txtSecondaryName = new javax.swing.JTextField();
    jLabel49 = new javax.swing.JLabel();
    txtSeondaryEmailAddress = new javax.swing.JTextField();
    jLabel47 = new javax.swing.JLabel();
    jLabel54 = new javax.swing.JLabel();
    txtCoverageEmailAddress = new javax.swing.JTextField();
    txtBusinessUnitDirector = new javax.swing.JTextField();
    jLabel55 = new javax.swing.JLabel();
    jLabel51 = new javax.swing.JLabel();
    jLabel52 = new javax.swing.JLabel();
    txtBUDEmailAddress = new javax.swing.JTextField();
    jLabel59 = new javax.swing.JLabel();
    txtFunctionalAreaLead = new javax.swing.JTextField();
    jLabel43 = new javax.swing.JLabel();
    txtPrimaryCoordinatorName = new javax.swing.JTextField();
    txtCoverageName = new javax.swing.JTextField();
    jLabel44 = new javax.swing.JLabel();
    txtPrimaryEmailAddress = new javax.swing.JTextField();
    jLabel58 = new javax.swing.JLabel();
    txtFALEmailAddress = new javax.swing.JTextField();
    jLabel62 = new javax.swing.JLabel();
    txtPrimaryPhoneNumber = new javax.swing.JTextField();
    jLabel48 = new javax.swing.JLabel();
    txtSecondaryPhoneNumber = new javax.swing.JTextField();
    jLabel53 = new javax.swing.JLabel();
    txtBUDPhoneNumber = new javax.swing.JTextField();
    txtCoveragePhoneNumber = new javax.swing.JTextField();
    jLabel56 = new javax.swing.JLabel();
    txtFALPhoneNumber = new javax.swing.JTextField();
    jLabel60 = new javax.swing.JLabel();
    pnlCRList = new javax.swing.JPanel();
    scrCRList = new javax.swing.JScrollPane();
    templatesList = new DefaultListModel();
    lstCRTemplates = new javax.swing.JList(templatesList);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sabre/hd/resources/images/cancel.png"))); // NOI18N
    btnClose.setText("Close");

    btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sabre/hd/resources/images/page.png"))); // NOI18N
    btnNew.setText("New");

    btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sabre/hd/resources/images/folder_add.png"))); // NOI18N
    btnLoad.setText("Load");
    btnLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoadActionPerformed(evt);
      }
    });

    btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sabre/hd/resources/images/disk.png"))); // NOI18N
    btnSave.setText("Save");
    btnSave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSaveActionPerformed(evt);
      }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sabre/hd/resources/images/page_code.png"))); // NOI18N
    jButton1.setText("Execute Workflow");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
    pnlActions.setLayout(pnlActionsLayout);
    pnlActionsLayout.setHorizontalGroup(
      pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlActionsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
          .addComponent(btnLoad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
          .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
          .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlActionsLayout.setVerticalGroup(
      pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlActionsLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnSave)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnLoad)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnNew)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnClose)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel27.setText("Change Justification");

    jLabel8.setText("Environment");

    cmbEnvironment.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbEnvironmentActionPerformed(evt);
      }
    });

    cmbSponsor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbSponsorActionPerformed(evt);
      }
    });

    jLabel6.setText("Sponsor");

    jLabel15.setText("Associated Problem");

    jLabel4.setText("Manager ID");

    jLabel26.setText("Requested Type");

    txtChangeCategory.setText(" ");

    jLabel24.setText("Change Category");

    txtImpactDescription.setColumns(20);
    txtImpactDescription.setRows(5);
    jScrollPane1.setViewportView(txtImpactDescription);

    txtChangeJustification.setColumns(20);
    txtChangeJustification.setRows(5);
    jScrollPane10.setViewportView(txtChangeJustification);

    jLabel33.setText("Impact Description");

    jLabel1.setText("Phone Number");

    cmbChangeName.setText(" ");

    jLabel2.setText("External Reference ID");

    jLabel29.setText("State");

    jLabel12.setText("Description");

    jLabel31.setText("Current Status");

    jLabel11.setText("Change Name");

    txtDescription.setColumns(20);
    txtDescription.setRows(5);
    jScrollPane7.setViewportView(txtDescription);

    txtAssociatedProblem.setText(" ");

    javax.swing.GroupLayout pnlContactInformationLayout = new javax.swing.GroupLayout(pnlContactInformation);
    pnlContactInformation.setLayout(pnlContactInformationLayout);
    pnlContactInformationLayout.setHorizontalGroup(
      pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactInformationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactInformationLayout.createSequentialGroup()
            .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlContactInformationLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
              .addGroup(pnlContactInformationLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(2, 2, 2))
              .addGroup(pnlContactInformationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
              .addGroup(pnlContactInformationLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(5, 5, 5)))
            .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cmbSponsor, javax.swing.GroupLayout.Alignment.TRAILING, 0, 339, Short.MAX_VALUE)
              .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
              .addComponent(txtExternalReferenceID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
              .addComponent(txtManagerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactInformationLayout.createSequentialGroup()
            .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(pnlContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                      .addGroup(pnlContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(52, 52, 52))
                      .addGroup(pnlContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                      .addGroup(pnlContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                      .addGroup(pnlContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                    .addGroup(pnlContactInformationLayout.createSequentialGroup()
                      .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGap(24, 24, 24)))
                  .addGroup(pnlContactInformationLayout.createSequentialGroup()
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)))
                .addGroup(pnlContactInformationLayout.createSequentialGroup()
                  .addComponent(jLabel27)
                  .addGap(24, 24, 24)))
              .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel26))
            .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cmbRequestedType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 338, Short.MAX_VALUE)
              .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
              .addComponent(txtChangeCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
              .addComponent(cmbState, 0, 338, Short.MAX_VALUE)
              .addComponent(cmbCurrentStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 338, Short.MAX_VALUE)
              .addComponent(txtAssociatedProblem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
              .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
              .addComponent(cmbChangeName, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
              .addComponent(cmbEnvironment, javax.swing.GroupLayout.Alignment.TRAILING, 0, 338, Short.MAX_VALUE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))))
        .addContainerGap())
    );
    pnlContactInformationLayout.setVerticalGroup(
      pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlContactInformationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtExternalReferenceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel12)
          .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtAssociatedProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel15))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel31))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel29))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtChangeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel24))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel27)
          .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbRequestedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel26))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel33)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(130, Short.MAX_VALUE))
    );

    tbsCRForm.addTab("Contact Information", pnlContactInformation);

    jLabel28.setText("Priority");

    txtImplementationLocation.setText(" ");

    jLabel25.setText("Activity");

    txtHSIS.setText(" ");

    txtRiskReason.setColumns(20);
    txtRiskReason.setRows(5);
    jScrollPane11.setViewportView(txtRiskReason);

    txtOther.setText(" ");

    txtECO.setText(" ");
    txtECO.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtECOActionPerformed(evt);
      }
    });

    txtLMR.setText(" ");

    jLabel3.setText("Employee ID");

    jLabel30.setText("Component Type");

    txtEmployeeID.setText(" ");

    jLabel32.setText("Risk Reason");

    jTextField5.setText(" ");

    jLabel7.setText("Service Request #");

    jLabel5.setText("Developer/Vendor");

    jScrollPane2.setViewportView(cmbAssets);

    jLabel14.setText("Customers Impacted");

    txtEmailAddress.setText(" ");

    jLabel13.setText("Assets");

    jLabel10.setText("E-mail Address");

    jLabel16.setText("ECO");

    jLabel9.setText("Implementation Location");

    jLabel17.setText("HSIS");

    jLabel19.setText("Other");

    jLabel18.setText("LMR");

    txtCustomersImpacted.setText(" ");

    chkFirewallChange.setText("Change Relates to a Firewall");
    chkFirewallChange.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkFirewallChangeActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlClassificationLayout = new javax.swing.GroupLayout(pnlClassification);
    pnlClassification.setLayout(pnlClassificationLayout);
    pnlClassificationLayout.setHorizontalGroup(
      pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlClassificationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(chkFirewallChange, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtHSIS, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(txtECO, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(txtLMR, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(txtOther, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(cmbComponentType, javax.swing.GroupLayout.Alignment.LEADING, 0, 282, Short.MAX_VALUE)
              .addComponent(txtCustomersImpacted, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(txtImplementationLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(cmbDeveloperVendor, javax.swing.GroupLayout.Alignment.LEADING, 0, 282, Short.MAX_VALUE)
              .addComponent(txtEmployeeID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(cmbActivity, 0, 282, Short.MAX_VALUE)
              .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
              .addComponent(cmbPriority, 0, 282, Short.MAX_VALUE)
              .addComponent(txtEmailAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(333, 333, 333))
    );
    pnlClassificationLayout.setVerticalGroup(
      pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlClassificationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel10)
          .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addGap(7, 7, 7)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cmbDeveloperVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtImplementationLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtCustomersImpacted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel14))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cmbComponentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel30))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cmbActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel25))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cmbPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel28)))
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addGap(95, 95, 95)
            .addComponent(jLabel13)))
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(jLabel32))
          .addGroup(pnlClassificationLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtHSIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel17))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel16))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtLMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel18))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel19))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(chkFirewallChange)
        .addContainerGap(131, Short.MAX_VALUE))
    );

    tbsCRForm.addTab("Classification ", pnlClassification);

    chkEmergencyChange.setText("Emergency Change");
    chkEmergencyChange.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkEmergencyChangeActionPerformed(evt);
      }
    });

    chkAffectsMultiplyCustomers.setText("Affects Multiply Customers");
    chkAffectsMultiplyCustomers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkAffectsMultiplyCustomersActionPerformed(evt);
      }
    });

    chkSignificantChange.setText("Significant Change");
    chkSignificantChange.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkSignificantChangeActionPerformed(evt);
      }
    });

    chkAffectsCritical.setText("Affects Critical Hardware/software components");
    chkAffectsCritical.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkAffectsCriticalActionPerformed(evt);
      }
    });

    chkTechnicalTeam.setText("More than one Technical Team Required");
    chkTechnicalTeam.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkTechnicalTeamActionPerformed(evt);
      }
    });

    chkNewActivity.setText("New Activity ");
    chkNewActivity.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkNewActivityActionPerformed(evt);
      }
    });

    jLabel20.setText("Customer Impact");

    txtCustomerImpact.setText(" ");

    jRadioButton14.setText("0. Automated Change");
    jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton14ActionPerformed(evt);
      }
    });

    jRadioButton13.setText("5. Impact to all customers, environments, or a data center");

    jLabel46.setText("Potential Impact");

    jRadioButton16.setText("2. Impact to internal systems");

    jRadioButton18.setText("4. Impact to multiple customers or envronment");

    jRadioButton15.setText("1. No Impact");

    jRadioButton17.setText("3. Impact to single customer or environment");

    jRadioButton5.setText("4. High risk");
    jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton5ActionPerformed(evt);
      }
    });

    jLabel61.setText("Potential Risk");

    jRadioButton20.setText("1. No risk");
    jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton20ActionPerformed(evt);
      }
    });

    jRadioButton6.setText("3. Medium risk");

    jRadioButton19.setText("2. Low risk");

    javax.swing.GroupLayout pnlImpactAndRiskLayout = new javax.swing.GroupLayout(pnlImpactAndRisk);
    pnlImpactAndRisk.setLayout(pnlImpactAndRiskLayout);
    pnlImpactAndRiskLayout.setHorizontalGroup(
      pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
        .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(chkEmergencyChange)
          .addComponent(chkAffectsMultiplyCustomers)
          .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jRadioButton18)
              .addComponent(jRadioButton17)
              .addComponent(jRadioButton16)
              .addComponent(jRadioButton15)
              .addComponent(jRadioButton14)
              .addComponent(jRadioButton13)))
          .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
                .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel20)
                  .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerImpact, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(chkSignificantChange)
              .addComponent(chkTechnicalTeam)
              .addComponent(chkAffectsCritical)))
          .addComponent(chkNewActivity)
          .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addComponent(jLabel46))
          .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jRadioButton6)
              .addComponent(jRadioButton5)
              .addComponent(jRadioButton19)
              .addComponent(jRadioButton20))))
        .addContainerGap(302, Short.MAX_VALUE))
    );
    pnlImpactAndRiskLayout.setVerticalGroup(
      pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlImpactAndRiskLayout.createSequentialGroup()
        .addComponent(chkEmergencyChange)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkAffectsMultiplyCustomers)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkNewActivity)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel46)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton14)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton15)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton16)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jRadioButton17)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton18)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton13)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkTechnicalTeam)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkAffectsCritical)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkSignificantChange)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlImpactAndRiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel20)
          .addComponent(txtCustomerImpact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel61)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton20)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jRadioButton19)
        .addGap(3, 3, 3)
        .addComponent(jRadioButton6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton5)
        .addGap(205, 205, 205))
    );

    tbsCRForm.addTab("Impact and Risk ", pnlImpactAndRisk);

    txtDurationHH.setText(" ");

    txtDurationDD.setText(" ");

    jLabel40.setText("DD:HH:MM");

    txtDurationMM.setText(" ");

    jLabel42.setText(":");

    jLabel41.setText(":");

    chkASAP.setText("ASAP");
    chkASAP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkASAPActionPerformed(evt);
      }
    });

    chkDefault.setText("Default");

    txtStartDate.setText(" ");

    txtEndDate.setText(" ");

    jLabel36.setText("End Date");

    jLabel39.setText("Duration (Include Fallback Time)");

    txtEndTime.setText(" ");

    txtStartTime.setText(" ");
    txtStartTime.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtStartTimeActionPerformed(evt);
      }
    });

    jLabel38.setText("End Time");

    jLabel37.setText("Start Time");

    jLabel23.setText("Start Date");

    jLabel34.setText("Installation Procedure");

    jLabel35.setText("Fallback Procedure");

    txtInstallationProcedure.setColumns(20);
    txtInstallationProcedure.setRows(5);
    jScrollPane3.setViewportView(txtInstallationProcedure);

    txtFallbackProcedure.setColumns(20);
    txtFallbackProcedure.setRows(5);
    jScrollPane4.setViewportView(txtFallbackProcedure);

    javax.swing.GroupLayout pnlInstallaionAndFallbackLayout = new javax.swing.GroupLayout(pnlInstallaionAndFallback);
    pnlInstallaionAndFallback.setLayout(pnlInstallaionAndFallbackLayout);
    pnlInstallaionAndFallbackLayout.setHorizontalGroup(
      pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel37)
          .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
            .addGap(1, 1, 1)
            .addComponent(jLabel36))
          .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel23)
              .addComponent(jLabel38)
              .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(2, 2, 2)
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInstallaionAndFallbackLayout.createSequentialGroup()
                .addComponent(txtEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chkDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
              .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(chkASAP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
              .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)))
          .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInstallaionAndFallbackLayout.createSequentialGroup()
                .addComponent(txtDurationDD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDurationHH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDurationMM))
              .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING))
            .addGap(24, 24, 24)
            .addComponent(jLabel40)))
        .addContainerGap())
    );
    pnlInstallaionAndFallbackLayout.setVerticalGroup(
      pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel34))
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel35))
              .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel23))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel37)
              .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(chkASAP))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(pnlInstallaionAndFallbackLayout.createSequentialGroup()
            .addGap(292, 292, 292)
            .addComponent(jLabel36)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(chkDefault))
          .addComponent(jLabel38))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel39)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlInstallaionAndFallbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtDurationMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel40)
          .addComponent(txtDurationDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDurationHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel41)
          .addComponent(jLabel42))
        .addContainerGap(263, Short.MAX_VALUE))
    );

    tbsCRForm.addTab("Installation and Fallback ", pnlInstallaionAndFallback);

    txtInstallerID.setText(" ");

    jLabel50.setText("Installer ID");

    txtSecondaryName.setText(" ");

    jLabel49.setText("Secondary Name");

    txtSeondaryEmailAddress.setText(" ");

    jLabel47.setText("Seondary Email Address");

    jLabel54.setText("Coverage Email Address");

    txtCoverageEmailAddress.setText(" ");

    txtBusinessUnitDirector.setText(" ");

    jLabel55.setText("Coverage Name");

    jLabel51.setText("BUD Email Address");

    jLabel52.setText("Business Unit Director");

    txtBUDEmailAddress.setText(" ");

    jLabel59.setText("Functional Area Lead");

    txtFunctionalAreaLead.setText(" ");
    txtFunctionalAreaLead.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtFunctionalAreaLeadActionPerformed(evt);
      }
    });

    jLabel43.setText("Primary/Coordinator Name");

    txtPrimaryCoordinatorName.setText(" ");

    txtCoverageName.setText(" ");

    jLabel44.setText("Primary Email Address");

    txtPrimaryEmailAddress.setText(" ");

    jLabel58.setText("FAL Email Address");

    txtFALEmailAddress.setText(" ");

    jLabel62.setText("Primary Phone Number");

    txtPrimaryPhoneNumber.setText(" ");

    jLabel48.setText("Secondary Phone Number");

    txtSecondaryPhoneNumber.setText(" ");

    jLabel53.setText("BUD Phone Number");

    txtBUDPhoneNumber.setText(" ");

    txtCoveragePhoneNumber.setText(" ");

    jLabel56.setText("Coverage Phone Number");

    txtFALPhoneNumber.setText(" ");

    jLabel60.setText("FAL Phone Number");

    javax.swing.GroupLayout pnlSupportContactLayout = new javax.swing.GroupLayout(pnlSupportContact);
    pnlSupportContact.setLayout(pnlSupportContactLayout);
    pnlSupportContactLayout.setHorizontalGroup(
      pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlSupportContactLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel44)
          .addComponent(jLabel49)
          .addComponent(jLabel47)
          .addComponent(jLabel53)
          .addComponent(jLabel56)
          .addComponent(jLabel58)
          .addComponent(jLabel62)
          .addComponent(jLabel48)
          .addComponent(jLabel51)
          .addComponent(jLabel52)
          .addComponent(jLabel50)
          .addComponent(jLabel55)
          .addComponent(jLabel54)
          .addComponent(jLabel59)
          .addComponent(jLabel60))
        .addGap(48, 48, 48)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtFALPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtFunctionalAreaLead, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtCoverageEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtCoverageName, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtInstallerID, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtBusinessUnitDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtBUDEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtPrimaryPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtFALEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addComponent(txtSecondaryPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(txtCoveragePhoneNumber)
            .addComponent(txtBUDPhoneNumber)
            .addComponent(txtSeondaryEmailAddress)
            .addComponent(txtSecondaryName)
            .addComponent(txtPrimaryEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
      .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlSupportContactLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jLabel43)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
          .addComponent(txtPrimaryCoordinatorName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
    );
    pnlSupportContactLayout.setVerticalGroup(
      pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlSupportContactLayout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtPrimaryEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel44))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtSecondaryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel49))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtSeondaryEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel47))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtInstallerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel50))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtBusinessUnitDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel52))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtBUDEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel51))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtCoverageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel55))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtCoverageEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel54))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtFunctionalAreaLead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel59))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtFALEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel58))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtPrimaryPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel62))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel48)
          .addComponent(txtSecondaryPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtBUDPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel53))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel56)
          .addComponent(txtCoveragePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel60)
          .addComponent(txtFALPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(245, Short.MAX_VALUE))
      .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlSupportContactLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(pnlSupportContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txtPrimaryCoordinatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel43))
          .addContainerGap(633, Short.MAX_VALUE)))
    );

    tbsCRForm.addTab("Support Contact ", pnlSupportContact);

    lstCRTemplates.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    scrCRList.setViewportView(lstCRTemplates);

    javax.swing.GroupLayout pnlCRListLayout = new javax.swing.GroupLayout(pnlCRList);
    pnlCRList.setLayout(pnlCRListLayout);
    pnlCRListLayout.setHorizontalGroup(
      pnlCRListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCRListLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrCRList, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        .addContainerGap())
    );
    pnlCRListLayout.setVerticalGroup(
      pnlCRListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCRListLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrCRList, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(207, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(tbsCRForm, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(pnlActions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnlCRList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tbsCRForm, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlCRList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      if (saveSRTemplate()) {
        JOptionPane.showMessageDialog(this,
                "Your SR Template was succesfully Saved!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
      } else {
        JOptionPane.showMessageDialog(this,
                "Your SR Template could not be saved!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
      }
}//GEN-LAST:event_btnSaveActionPerformed

    private void chkASAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkASAPActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkASAPActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton14ActionPerformed

    private void chkNewActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNewActivityActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkNewActivityActionPerformed

    private void chkTechnicalTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTechnicalTeamActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkTechnicalTeamActionPerformed

    private void chkAffectsCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAffectsCriticalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkAffectsCriticalActionPerformed

    private void chkSignificantChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSignificantChangeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkSignificantChangeActionPerformed

    private void chkAffectsMultiplyCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAffectsMultiplyCustomersActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkAffectsMultiplyCustomersActionPerformed

    private void chkEmergencyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmergencyChangeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkEmergencyChangeActionPerformed

    private void chkFirewallChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFirewallChangeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkFirewallChangeActionPerformed

    private void cmbSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSponsorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSponsorActionPerformed

    private void cmbEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnvironmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnvironmentActionPerformed

    private void txtECOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtECOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtECOActionPerformed

    private void txtStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartTimeActionPerformed

    private void txtFunctionalAreaLeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFunctionalAreaLeadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFunctionalAreaLeadActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ChangeRequest aChangeRequest = Facade.loadDemoCR();
      Facade.executeSeleniumCR(aChangeRequest);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCRTemplate().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnLoad;
  private javax.swing.JButton btnNew;
  private javax.swing.JButton btnSave;
  private javax.swing.JCheckBox chkASAP;
  private javax.swing.JCheckBox chkAffectsCritical;
  private javax.swing.JCheckBox chkAffectsMultiplyCustomers;
  private javax.swing.JCheckBox chkDefault;
  private javax.swing.JCheckBox chkEmergencyChange;
  private javax.swing.JCheckBox chkFirewallChange;
  private javax.swing.JCheckBox chkNewActivity;
  private javax.swing.JCheckBox chkSignificantChange;
  private javax.swing.JCheckBox chkTechnicalTeam;
  private javax.swing.JComboBox cmbActivity;
  private javax.swing.JList cmbAssets;
  private javax.swing.JTextField cmbChangeName;
  private javax.swing.JComboBox cmbComponentType;
  private javax.swing.JComboBox cmbCurrentStatus;
  private javax.swing.JComboBox cmbDeveloperVendor;
  private javax.swing.JComboBox cmbEnvironment;
  private javax.swing.JComboBox cmbPriority;
  private javax.swing.JComboBox cmbRequestedType;
  private javax.swing.JComboBox cmbSponsor;
  private javax.swing.JComboBox cmbState;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel34;
  private javax.swing.JLabel jLabel35;
  private javax.swing.JLabel jLabel36;
  private javax.swing.JLabel jLabel37;
  private javax.swing.JLabel jLabel38;
  private javax.swing.JLabel jLabel39;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel40;
  private javax.swing.JLabel jLabel41;
  private javax.swing.JLabel jLabel42;
  private javax.swing.JLabel jLabel43;
  private javax.swing.JLabel jLabel44;
  private javax.swing.JLabel jLabel46;
  private javax.swing.JLabel jLabel47;
  private javax.swing.JLabel jLabel48;
  private javax.swing.JLabel jLabel49;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel50;
  private javax.swing.JLabel jLabel51;
  private javax.swing.JLabel jLabel52;
  private javax.swing.JLabel jLabel53;
  private javax.swing.JLabel jLabel54;
  private javax.swing.JLabel jLabel55;
  private javax.swing.JLabel jLabel56;
  private javax.swing.JLabel jLabel58;
  private javax.swing.JLabel jLabel59;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel60;
  private javax.swing.JLabel jLabel61;
  private javax.swing.JLabel jLabel62;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JRadioButton jRadioButton13;
  private javax.swing.JRadioButton jRadioButton14;
  private javax.swing.JRadioButton jRadioButton15;
  private javax.swing.JRadioButton jRadioButton16;
  private javax.swing.JRadioButton jRadioButton17;
  private javax.swing.JRadioButton jRadioButton18;
  private javax.swing.JRadioButton jRadioButton19;
  private javax.swing.JRadioButton jRadioButton20;
  private javax.swing.JRadioButton jRadioButton5;
  private javax.swing.JRadioButton jRadioButton6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane10;
  private javax.swing.JScrollPane jScrollPane11;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane7;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JList lstCRTemplates;
  private javax.swing.JPanel pnlActions;
  private javax.swing.JPanel pnlCRList;
  private javax.swing.JPanel pnlClassification;
  private javax.swing.JPanel pnlContactInformation;
  private javax.swing.JPanel pnlImpactAndRisk;
  private javax.swing.JPanel pnlInstallaionAndFallback;
  private javax.swing.JPanel pnlSupportContact;
  private javax.swing.JScrollPane scrCRList;
  private javax.swing.JTabbedPane tbsCRForm;
  private javax.swing.JTextField txtAssociatedProblem;
  private javax.swing.JTextField txtBUDEmailAddress;
  private javax.swing.JTextField txtBUDPhoneNumber;
  private javax.swing.JTextField txtBusinessUnitDirector;
  private javax.swing.JTextField txtChangeCategory;
  private javax.swing.JTextArea txtChangeJustification;
  private javax.swing.JTextField txtCoverageEmailAddress;
  private javax.swing.JTextField txtCoverageName;
  private javax.swing.JTextField txtCoveragePhoneNumber;
  private javax.swing.JTextField txtCustomerImpact;
  private javax.swing.JTextField txtCustomersImpacted;
  private javax.swing.JTextArea txtDescription;
  private javax.swing.JTextField txtDurationDD;
  private javax.swing.JTextField txtDurationHH;
  private javax.swing.JTextField txtDurationMM;
  private javax.swing.JTextField txtECO;
  private javax.swing.JTextField txtEmailAddress;
  private javax.swing.JTextField txtEmployeeID;
  private javax.swing.JTextField txtEndDate;
  private javax.swing.JTextField txtEndTime;
  private javax.swing.JTextField txtExternalReferenceID;
  private javax.swing.JTextField txtFALEmailAddress;
  private javax.swing.JTextField txtFALPhoneNumber;
  private javax.swing.JTextArea txtFallbackProcedure;
  private javax.swing.JTextField txtFunctionalAreaLead;
  private javax.swing.JTextField txtHSIS;
  private javax.swing.JTextArea txtImpactDescription;
  private javax.swing.JTextField txtImplementationLocation;
  private javax.swing.JTextArea txtInstallationProcedure;
  private javax.swing.JTextField txtInstallerID;
  private javax.swing.JTextField txtLMR;
  private javax.swing.JTextField txtManagerID;
  private javax.swing.JTextField txtOther;
  private javax.swing.JTextField txtPhoneNumber;
  private javax.swing.JTextField txtPrimaryCoordinatorName;
  private javax.swing.JTextField txtPrimaryEmailAddress;
  private javax.swing.JTextField txtPrimaryPhoneNumber;
  private javax.swing.JTextArea txtRiskReason;
  private javax.swing.JTextField txtSecondaryName;
  private javax.swing.JTextField txtSecondaryPhoneNumber;
  private javax.swing.JTextField txtSeondaryEmailAddress;
  private javax.swing.JTextField txtStartDate;
  private javax.swing.JTextField txtStartTime;
  // End of variables declaration//GEN-END:variables

  private DefaultListModel templatesList;

  private boolean saveSRTemplate() {
    return true;
  }

}
